### ISSUE TITLE
The WWW url not working

### ISSUE THREAD

**Issue by Pyush** [BetaHuhn/metadata-scraper#141]
Let me describe when I enter the URL as "www.bluehost.in" it's throwing an error Invalid URL.

const getMetaData = require('metadata-scraper')
const data = await getMetaData('www.bluehost.in')

It's throw an error shown in below screenshot.

**🖼️ Screenshots**

![image](https://user-images.githubusercontent.com/5697614/130359659-06416235-46f1-4346-b565-07087fb8f6db.png)

**⚙️ Environment**
 - OS: [e.g. Ubuntu 18.04]
 - Node.js Version [e.g. v14]
 - Link to website

**Comment by BetaHuhn** [comment]
As the error indicates, `www.bluehost.in` is not a valid URL as there is no protocol specified. You will get the same error when you run `new URL('www.bluehost.in')` in your browser console.

`https://www.bluehost.in` should work.

**Comment by BetaHuhn** [comment]
We could consider adding the protocol automatically to the provided URL if it is missing

**Comment by Pyush** [comment]
```
const withHttp = (url) => url.replace(/^(?:(.*:)?\/\/)?(.*)/i, (match, schemma, nonSchemmaUrl) => schemma ? match : `http://${nonSchemmaUrl}`);

alert(withHttp("www.google.com"));
alert(withHttp("google.com"));
alert(withHttp("//google.com"));
alert(withHttp("http://www.google.com/"));
alert(withHttp("https://www.google.com/"));
alert(withHttp("ftp://www.google.com"));
alert(withHttp("username:password@localhost:257/deploy/?asd=asd#asd"));
alert(withHttp("test.example.com/dir/subdir/file.html#hash"));
alert(withHttp("http://test.example.com/dir/subdir/file.html#hash"));
```

A Snippet if it's help. Thank You.!
