### ISSUE TITLE
Request to web.com blocked by Cloudflare

### ISSUE THREAD

**Issue by ogurinkaben** [BetaHuhn/metadata-scraper#156]
**🐞 Describe the bug**

I am building a service that requires me to fetch metadata from any given URL.
This isn't at the center of what I am working on, it's an addon feature and after some Google search I found this package (cool stuff)

When working with most URLs and fetching data everything seems to work fine.
But whenever I try to retrieve metadata from http://web.com, it throws an error.

**📚 To Reproduce**

Try fetching metadata for http://web.com

**💡 Expected behavior**
I expect to get results with the metadata from the URL instead I get
```
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/root/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1632256779506,
    socket: 1632256779517,
    lookup: 1632256779568,
    connect: 1632256779579,
    secureConnect: 1632256779602,
    upload: 1632256779602,
    response: 1632256779759,
    end: 1632256779809,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 11,
      dns: 51,
      tcp: 11,
      tls: 23,
      request: 0,
      firstByte: 157,
      download: 50,
      total: 303
    }
  }
}
```

**🖼️ Screenshots**

https://scrnli.com/CV2MNqySiJMIeS

**⚙️ Environment**
 - OS: Linux Mint 20
 - Node.js Version: v12.16.3
 - Link to website

**📋 Additional context**

**Comment by BetaHuhn** [comment]
Looks like http://web.com is blocking the request, this is not an error with `metadata-scraper` by itself.

When requesting http://web.com using curl `curl -L http://web.com` I get the same error and a Cloudflare captcha page.

**Comment by BetaHuhn** [comment]
No not really. Cloudflare is somehow detecting that the request is automated and asks the client to perform a captcha.

Those issues usually only come up when the request comes from a server with high traffic/when performing a lot of requests from a known IP and not when running it locally.

Maybe [#140](https://github.com/BetaHuhn/metadata-scraper/discussions/140) i.e. running the JavaScript from the site and actually rendering it in a browser could help prevent the request from being blocked by Cloudflare. Not sure though, feel free to investigate this yourself and let me know what comes up!

**Comment by ogurinkaben** [comment]
I found a temporary fix for what I am working on.
It is not a fix that directly concerns the package, just had to change the structure of my code to better handle a case like this a bit better. I ran a lot of tests and the issue persists for a couple of sites away from web.com.

**Comment by BetaHuhn** [comment]
Okay great! For the actual issue there's not much that can be done. Some sites will always try to block automated traffic.

I will see if #140 would reduce the likelihood of requests being blocked, but it would require to spin up a headless chrome instance for each request which is not ideal.

Will close this issue for now, but feel free to comment if you find a workaround/a way to bypass the block.
